baseURL = '/'
languageCode = 'zh-CN'
title = '花思'
disableKinds = ['taxonomy', 'term']
minify = true
publishDir = 'public'

[params]
    subTitle = '花点心思，遇见更好的自己'
    keywords = '花思,花心思,花点心思,花思科技,花思网,花思公司'
    description = '花点心思，遇见更好的你。一家为你花心思的公司'
    avatar = ''
    siteName = '花思科技'
    siteDescription = '花点心思，遇见更好的你。一家为你花心思的公司'

[[params.head.cssFile]]
    link = ''

[[params.foot.jsFile]]
    link = 'https://cdn.huasikeji.com/libs/flowbite/2.3.0/flowbite.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.huasikeji.com/libs/wesome-qr/2.1.5-rc.0/awesome-qr.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.huasikeji.com/libs/html2canvas/html2canvas.min.js'
[[params.foot.jsFile]]
    link = ''

[params.footer]
    startDate = 2024
    #icp = ''
[params.footer.police]
    #number = 
    text = ''

